### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.eventinvitation#11]
- [x] Analyse code regarding PHP 8 compatibility
- [x] Fix deprecations found (to be specified)

_systopia-reference: 19909_

**Comment by jofranz** [comment]
@jensschuppe I see this error from code scans quite often. Is this something we need to fix or does it work anyway?:

```de.systopia.eventinvitation/CRM/Eventinvitation/Form/Task/ContactSearch.php
---------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------
 323 | ERROR | The default value of the $flags parameter for 
 html_entity_decode() was changed from ENT_COMPAT to
     |       | ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401 in PHP 8.1. For cross-version compatibility, the $flags
     |       | parameter should be explicitly set.
---------------------------------------------------------------------------------------------------------------------
```

_systopia-reference: 19909_

**Comment by jensschuppe** [comment]
Actually the only usage of `html_entity_decode()` in this extension is https://github.com/systopia/de.systopia.eventinvitation/blob/4ee940670a914d90887a2e9ddf9d50542f102bba/CRM/Eventinvitation/Form/Task/ContactSearch.php#L323 which git blames on you, @bjendres :wink:

[Anyway](https://php.watch/versions/8.1/html-entity-default-value-changes):
> From PHP 8.1 and later, the default parameters of these functions are changed, so that it also converts single quote characters. In contrast to the prior behavior of returning an empty string for a string that contains an invalid character, the default behavior of these functions in PHP 8.1 and later is to substitute invalid characters with � (U+FFFD) characters.

which seems fine for me with what we expect in there (a path), so keeping the new default behavior is ok, no change needed, I'd say.

I actually wonder why decoding HTML entities would be necessary in the first place ...
