### ISSUE TITLE
Does this extension send an iCal invite?

### ISSUE THREAD

**Issue by Upperholme** [systopia/de.systopia.eventinvitation#14]
Thanks for this extension. It's not clear from the documentation what this extension sends? II'm looking for a solution that will send an iCal format invitation that will appear in recipients' calendar applications.

**Comment by bjendres** [comment]
As far as a I remember it can do that with the help of https://github.com/systopia/de.systopia.mailattachment and https://github.com/systopia/de.systopia.eventmessages, but @jensschuppe might know better.

**Comment by Fabian-SYSTOPIA** [comment]
This extension creates participant objects for the selected contacts with the status invited. They can then respond using a feedback form - it does not contain an iCal-file at firts. As Björn has mentioned you may achieve this with other extensions.

**Comment by jensschuppe** [comment]
Correct, this extension does not (yet) support attachments, but it could by implementing https://github.com/systopia/de.systopia.mailattachment. We currently do not have plans to do that, so this would require a PR by someone else or funding.

You can, however, use https://github.com/systopia/de.systopia.eventmessages to send (another) e-mail message when the participant status changes to "Invited" and attach an iCal file there. This would have to be configured per event.

**Comment by Upperholme** [comment]
Thanks for the helpful feedback.
